# Numpy array module

In [1]:
%time print("a") #this returns the time required for the data to interprete

a
CPU times: user 415 µs, sys: 70 µs, total: 485 µs
Wall time: 322 µs


In [2]:
import numpy as np
ar = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]],dtype ='float')
print(ar)


[[1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]]


In [3]:
ar.shape #this returns the number of columns and rows

(2, 6)

In [4]:
ar.dtype #this returns the data type of the elements of the array

dtype('float64')

In [15]:
np.ones((7,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
arr = np.array([[1,2,3,4,5,6],
                [3,4,5,6,7,8],[1,7,8,9,5,4,]])
print(arr)

print("-------------------------------------")
arr2 = np.array([[2,3,5,6,7,8],
                [3,4,5,6,7,8]])
print(arr2)


[[1 2 3 4 5 6]
 [3 4 5 6 7 8]
 [1 7 8 9 5 4]]
-------------------------------------
[[2 3 5 6 7 8]
 [3 4 5 6 7 8]]


In [7]:
#column sum
arr.sum(axis = 1)


array([21, 33, 34])

In [8]:
#row sum
arr.sum(axis = 0)


array([ 5, 13, 16, 19, 17, 18])

In [9]:
np.sort(arr,kind ='quicksort')

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8],
       [1, 4, 5, 7, 8, 9]])

In [18]:
c = np.array([1,2,3,4,5,67,44,55,65,76,34,57,34,87,32,52,67,23])
print(c)
print("------------------------------")
d = c.reshape(3,6)  #this reshape array to desired arguments
print(d)

[ 1  2  3  4  5 67 44 55 65 76 34 57 34 87 32 52 67 23]
------------------------------
[[ 1  2  3  4  5 67]
 [44 55 65 76 34 57]
 [34 87 32 52 67 23]]


In [11]:
#this sort elements indexes
np.argsort(c)

array([ 0,  1,  2,  3,  4, 17, 14, 10, 12,  6, 15,  7, 11,  8, 16,  5,  9,
       13])

In [21]:
np.argsort(d, axis = 0) #sort column wise

array([[0, 0, 0, 0, 0, 2],
       [2, 1, 2, 2, 1, 1],
       [1, 2, 1, 1, 2, 0]])

In [22]:
np.argsort(d,axis = 1) #sort row wise

array([[0, 1, 2, 3, 4, 5],
       [4, 0, 1, 5, 2, 3],
       [5, 2, 0, 3, 4, 1]])

In [16]:
np.argmin(c) #returns the min index of  the number

0

In [17]:
np.argmax(c) #returns the max index of the number

13